table Clients
	lineageTag: a44a4b4c-64ac-465a-b521-ab36020220ea

	column ClientID
		dataType: int64
		formatString: 0
		lineageTag: d612f1ae-1c88-40e1-8c89-869dfc82e687
		summarizeBy: none
		sourceColumn: ClientID

		annotation SummarizationSetBy = Automatic

	column ClientName
		dataType: string
		lineageTag: 132d5a42-18ad-4535-93ff-9fec7e792739
		summarizeBy: none
		sourceColumn: ClientName

		annotation SummarizationSetBy = Automatic

	column Town
		dataType: string
		lineageTag: bcaf76b0-bb77-44d1-a208-ae9e592cfe30
		dataCategory: City
		summarizeBy: none
		sourceColumn: Town

		annotation SummarizationSetBy = Automatic

	column CountryID
		dataType: int64
		formatString: 0
		lineageTag: a08b09e0-1070-4a47-a6dc-59ecef4571ed
		summarizeBy: none
		sourceColumn: CountryID

		annotation SummarizationSetBy = Automatic

	column ClientType
		dataType: string
		lineageTag: 99e22b93-3c75-49ca-9812-cd6a90155cdd
		summarizeBy: none
		sourceColumn: ClientType

		annotation SummarizationSetBy = Automatic

	column ClientSize
		dataType: string
		lineageTag: 355e156c-ad3f-473b-bcf5-28128ca1a670
		summarizeBy: none
		sourceColumn: ClientSize

		annotation SummarizationSetBy = Automatic

	column ClientSince
		dataType: dateTime
		formatString: General Date
		lineageTag: e6d93a87-1a17-4a47-bf06-e4118050f117
		summarizeBy: none
		sourceColumn: ClientSince

		variation Variation
			isDefault
			relationship: b608644a-790a-4dbe-a5e5-93f08f6526f4
			defaultHierarchy: LocalDateTable_512dbaf1-fd31-4c91-ba03-77364a38a602.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column IsCreditWorthy
		dataType: int64
		formatString: 0
		lineageTag: b0da22a2-af8c-434d-b8e3-374470f91aeb
		summarizeBy: sum
		sourceColumn: IsCreditWorthy

		annotation SummarizationSetBy = Automatic

	column WebSite
		dataType: string
		lineageTag: d68edd40-67b0-40d9-9b9f-012ee88a2342
		dataCategory: WebUrl
		summarizeBy: none
		sourceColumn: WebSite

		annotation SummarizationSetBy = Automatic

	partition Clients = m
		mode: import
		queryGroup: 'Sales Performance'
		source =
				let
				    Source = Pdf.Tables(File.Contents("C:\9EXPERT-Case Study Power BI Desktop-Version 30\Datasources\Clients.pdf"), [Implementation="1.3"]),
				    Table001 = Source{[Id="Table001"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Table001, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ClientID", Int64.Type}, {"ClientName", type text}, {"Address1", type text}, {"Address2", type text}, {"Town", type text}, {"County", type text}, {"PostCode", type text}, {"CountryID", Int64.Type}, {"ClientType", type text}, {"ClientSize", type text}, {"ClientSince", type text}, {"IsCreditWorthy", Int64.Type}, {"WebSite", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Address1", "Address2", "County", "PostCode"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Removed Columns",null,"Medium",Replacer.ReplaceValue,{"ClientSize"}),
				    #"Changed Type with Locale" = Table.TransformColumnTypes(#"Replaced Value", {{"ClientSince", type datetime}}, "en-GB")
				in
				    #"Changed Type with Locale"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

