table DimDate
	lineageTag: de66d818-9c9e-4073-93ff-1f868410ef59

	column DateKey
		dataType: dateTime
		formatString: dd-mmm-yy
		lineageTag: 06046a12-5b1c-4b13-9ba0-6ae166394257
		summarizeBy: none
		sourceColumn: DateKey

		variation Variation
			isDefault
			relationship: 316acbc3-9d63-4ae7-99b4-16ca92f354fc
			defaultHierarchy: LocalDateTable_76330710-85e5-4ae5-8817-785ec8fd31f7.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column Year
		dataType: int64
		formatString: 0
		lineageTag: a2a5ab51-c826-482d-97d9-1fc21f44a674
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = User

	column FisYear
		dataType: int64
		formatString: 0
		lineageTag: 563e263e-4b9d-44a5-b09a-dbe33872eab4
		summarizeBy: none
		sourceColumn: FisYear

		annotation SummarizationSetBy = User

	column MonthNum
		dataType: int64
		formatString: 0
		lineageTag: 3852edf3-f92a-470a-9751-f1b26a7f4cf2
		summarizeBy: none
		sourceColumn: MonthNum

		annotation SummarizationSetBy = User

	column MonthFull
		dataType: string
		lineageTag: f952b101-2380-4988-8c97-34fefd6c5745
		summarizeBy: none
		sourceColumn: MonthFull

		annotation SummarizationSetBy = Automatic

	column MonthAbbr
		dataType: string
		lineageTag: c62e1a47-be19-414f-a68a-15841f8c2a4b
		summarizeBy: none
		sourceColumn: MonthAbbr

		annotation SummarizationSetBy = Automatic

	column QuarterNum
		dataType: int64
		formatString: 0
		lineageTag: fa8203d7-f1fb-4466-b15e-ede3b0c692e5
		summarizeBy: none
		sourceColumn: QuarterNum

		annotation SummarizationSetBy = User

	column QuarterFull
		dataType: string
		lineageTag: 19dd004d-9b92-4ee0-88c1-35f0b9a52c56
		summarizeBy: none
		sourceColumn: QuarterFull

		annotation SummarizationSetBy = Automatic

	column QuarterNameAbbr
		dataType: string
		lineageTag: f9fe7b91-5a01-4bd6-b822-4f9a2a415cf2
		summarizeBy: none
		sourceColumn: QuarterNameAbbr

		annotation SummarizationSetBy = Automatic

	column YearAndQuarterNum
		dataType: int64
		formatString: 0
		lineageTag: f5bd2f22-2775-40f5-b0bd-612aaa580463
		summarizeBy: none
		sourceColumn: YearAndQuarterNum

		annotation SummarizationSetBy = User

	column YearAndMonthNum
		dataType: int64
		formatString: 0
		lineageTag: 539f3113-4f23-4308-a8ad-384646ed76b6
		summarizeBy: none
		sourceColumn: YearAndMonthNum

		annotation SummarizationSetBy = User

	column MonthAndYear
		dataType: string
		lineageTag: bdb6c41a-6a7f-4161-947f-aa1340fdc166
		summarizeBy: none
		sourceColumn: MonthAndYear
		sortByColumn: YearAndMonthNum

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column QuarterAndYear
		dataType: string
		lineageTag: dacf0384-4be8-4eeb-9bd3-4ec69f8f3233
		summarizeBy: none
		sourceColumn: QuarterAndYear
		sortByColumn: YearAndQuarterNum

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition DimDate = m
		mode: import
		queryGroup: 'Sales Performance'
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\9EXPERT-Case Study Power BI Desktop-Version 30\Datasources\DateTable.xlsx"), null, true),
				    DimFiscalCalendar4_Table = Source{[Item="DimFiscalCalendar4",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(DimFiscalCalendar4_Table,{{"DateKey", type date}, {"Year", Int64.Type}, {"FisYear", Int64.Type}, {"MonthNum", Int64.Type}, {"MonthFull", type text}, {"MonthAbbr", type text}, {"QuarterNum", Int64.Type}, {"QuarterFull", type text}, {"QuarterNameAbbr", type text}, {"YearAndQuarterNum", Int64.Type}, {"YearAndMonthNum", Int64.Type}, {"MonthAndYearAbbr", type text}, {"MonthAndYear", type text}, {"QuarterAndYearAbbr", type text}, {"QuarterAndYear", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"MonthAndYearAbbr", "QuarterAndYearAbbr"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

